name: 'ipl_warehouse'
version: '0.1.0'
config-version: 2

profile: 'ipl_warehouse'

model-paths: ["models"]
seed-paths: ["seeds"]
test-paths: ["tests"]
analysis-paths: ["analyses"]
macro-paths: ["macros"]
snapshot-paths: ["snapshots"]

target-path: "target"
clean-targets:
  - "target"
  - "dbt_packages"

models:
  ipl_warehouse:
    silver:
      +schema: silver
      +materialized: view
    gold:
      +schema: gold
      +materialized: view
